language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8
  - pyre
  - coverage run  --source=. tests.py
after_success:
  - coveralls
